spring:
  security:
    oauth2:
      client:
        provider: #???, ???? ?? provider? ??????.
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

        registration:
          facebook:
            client-id: 2607869126036663
            client-secret: b52e4c3065dd47364215f123bb588d66
            scope:
              - public_profile
              - email

          google:
            clientId: 868740993779-5utgmcadcm1j3bbpeji2l6vhgg8pbfke.apps.googleusercontent.com
            clientSecret: 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
            redirect-uri: http://localhost/login/oauth2/code/google
            scope:
              - email
              - profile

          naver:
            clientId: XDcUWz4KKsbw3HBne45K
            client-secret: rqPfSYd4rq
            redirect-uri: http://localhost/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile_image
            client-name: Naver

          kakao:
            clientId: 5759f9f5c643dab28f7ff2776ceff1eb
            client-secret: 16UfkfXNm85rr9mwpvJl6xrCUkdC35Un
            redirect-uri: http://localhost/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
              - profile_image
            client-name: Kakao
            client-authentication-method: POST